openapi: 3.0.0

info:
  title: mf-demo
  description: A simple todo application.
  version: 1.0.0

servers:
  - url: /api

paths:
  /remember-todo:
    post:
      summary: Remembers a todo.
      tags:
        - commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  minLength: 1
              additionalProperties: false
              required:
                - text
      responses:
        "200":
          description: The ID of the remembered todo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
        "400":
          description: Bad request

  /edit-todo:
    post:
      summary: Edits a todo.
      tags:
        - commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                text:
                  type: string
                  minLength: 1
                expectedRevision:
                  type: integer
                  minimum: 0
              additionalProperties: false
              required:
                - id
                - text
                - expectedRevision
      responses:
        "200":
          description: The todo was edited.
          content:
            application/json:
              schema:
                type: object
                properties:
        "400":
          description: Bad request.
        "404":
          description: Not found.

  /complete-todo:
    post:
      summary: Completes a todo.
      tags:
        - commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                expectedRevision:
                  type: integer
                  minimum: 0
              additionalProperties: false
              required:
                - id
                - expectedRevision
      responses:
        "200":
          description: The todo was completed.
          content:
            application/json:
              schema:
                type: object
                properties:
        "400":
          description: Bad request.
        "404":
          description: Not found.

  /todos:
    get:
      summary: Retrieves all pending todos.
      tags:
        - queries
      responses:
        "200":
          description: All pending todos.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    text:
                      type: string
                    revision:
                      type: integer

  /statistics:
    get:
      summary: Retrieves statistics.
      tags:
        - queries
      responses:
        "200":
          description: Statistics.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: integer
